# Generated by Django 4.1.5 on 2023-02-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_backend', '0003_alter_shop_user_alter_shop_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='state',
            field=models.BooleanField(default=False, verbose_name='Статус приема заказов'),
        ),
    ]
