# Generated by Django 4.1.5 on 2023-02-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_backend', '0004_alter_shop_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Статус приема заказов'),
        ),
    ]
