# Generated by Django 4.1.5 on 2023-02-13 17:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_backend', '0006_category_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=80, verbose_name='Модель')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_in_shops', to='shop_backend.product', verbose_name='Товар')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_in_shops', to='shop_backend.shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Товар магазина',
                'verbose_name_plural': 'Список товаров магазина',
            },
        ),
        migrations.AddConstraint(
            model_name='productinshop',
            constraint=models.UniqueConstraint(fields=('shop', 'product', 'model'), name='unique_product_in_shop'),
        ),
    ]
