# Generated by Django 4.1.5 on 2023-02-15 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_backend', '0007_productinshop_productinshop_unique_product_in_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Значение')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_parameters', to='shop_backend.parameter', verbose_name='Параметр')),
                ('product_in_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_parameters', to='shop_backend.productinshop', verbose_name='Товар магазина')),
            ],
            options={
                'verbose_name': 'Параметр товара',
                'verbose_name_plural': 'Список параметров товара',
            },
        ),
        migrations.AddConstraint(
            model_name='productparameter',
            constraint=models.UniqueConstraint(fields=('product_in_shop', 'parameter'), name='unique_product_parameter'),
        ),
    ]
