# Generated by Django 4.1.5 on 2023-02-18 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_backend', '0008_productparameter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_positions', to='shop_backend.productinshop', verbose_name='Позиция к заказу')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_positions', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Позиция корзины для заказа',
                'verbose_name_plural': 'Список позиций корзины для заказа',
            },
        ),
        migrations.AddConstraint(
            model_name='basketposition',
            constraint=models.UniqueConstraint(fields=('user', 'position'), name='unique_basket_position'),
        ),
    ]
